/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Rebirth": "重生",
    "Rebirths": "重生",
    "rebirth points": "重生点数",
    "Lose all previous progress and Rebirth.": "失去之前所有的进度和重生。",
    "This button will redirect you an older version if you have lost your save": "如果您丢失了存档，此按钮将重定向到旧版本",
    "Achievement Gotten!": "成就获得！",
    "It begins..": "开始了..",
    "Prestige": "声望",
    "All Star": "全明星",
    "A second digit!": "第二个数字！",
    "A very mini timewall": "一个非常小的时间墙",
    "Achievements are boosting point gain by": "成就提升了点数",
    "Achievements are useful again": "成就也是有用的",
    "All ten": "全部十个",
    "An upgrade": "升级",
    "Another Buyout": "另一次买断",
    "Another layer!": "另一层！",
    "Anti challenged": "反挑战",
    "Beat 'Unilayer' once": "击败“单层”一次",
    "Beat Feature Disablation three times": "击败功能禁用三次",
    "beat the first challenge once": "完成第一个挑战一次",
    "beat the second challenge once": "完成第二个挑战一次",
    "Billionare": "亿万富翁",
    "Boosers are getting even more useless": "鼻屎变得越来越没用了",
    "Boosters are getting useless": "助推器越来越没用了",
    "Boosts": "提升",
    "Buy 6 collapse upgrades": "购买6个坍缩升级",
    "Buy a collapse upgrade": "买一个坍缩的升级",
    "Buy all 4 collapse upgrades": "购买全部4个崩塌升级",
    "Buyout": "买断",
    "Cleansed": "洁净",
    "Collapse Millionare": "坍缩百万富翁",
    "Collapse with 20 collapse sacrifices": "用20个毁灭牺牲毁灭",
    "Complete a collapse run with all 25 sacrifices": "用全部25个牺牲完成一次坍缩跑",
    "Complete a collapse run with all 25 sacrifices inside of Total point breakdown": "完成一场坍缩跑，所有25个牺牲都在总分内",
    "Complete a run with eight or more sacrifices": "用8个或更多的牺牲完成一场比赛",
    "Complete a run with five or more sacrifices": "用五个或更多的牺牲完成一场比赛",
    "Complete a run with four or more sacrifices": "用四个或更多的牺牲完成一场比赛",
    "Complete a run with one or more sacrifices": "用一个或多个牺牲完成一场比赛",
    "Complete a run with seven or more sacrifices": "用七个或更多的牺牲完成一场比赛",
    "Complete a run with six or more sacrifices": "用6个或更多的牺牲完成一场比赛",
    "Complete a run with three or more sacrifices": "用三个或更多的牺牲完成一场比赛",
    "Complete a run with two or more sacrifices": "用两个或更多的牺牲完成一场比赛",
    "Deca-boosters": "十元助推器",
    "Diamond": "钻石",
    "Double Sacrifices": "双重牺牲",
    "Energetic": "精力充沛",
    "Energy collector": "能量收集器",
    "Energy Surge": "能量激增",
    "Enter Space": "进入空间",
    "Enter Void": "进入虚空",
    "Featureless": "无特色",
    "Finally, some automation!": "最后，一些自动化！",
    "get a mini rebirth point": "获得一个迷你重生点",
    "Get one rebirth": "获得重生",
    "Get three rebirths": "获得三次重生",
    "Get to the 12th rebirth": "进入第12次重生",
    "Get to the 6th minirebirth": "进入第六次迷你重生",
    "Get two rebirths": "获得两次重生",
    "Get your 8th rebirth": "获得第八次重生",
    "Get your 9th rebirth": "获得第九次重生",
    "Get your first collapse point": "获得第一个坍缩点",
    "Getting them all": "把它们都拿出来",
    "Googol^10 Points": "天文数字^ 10分",
    "Gotta get them all": "我要把他们都拿下",
    "Have all U-layer upgrades at once": "让所有U层同时升级",
    "Have atleast 53 upgrade points at once": "一次至少有53个升级点",
    "Have both layer-3 Space upgrades at once": "同时升级3层空间",
    "Here we go again!": "又来了！",
    "Hexasacrifices": "六元牺牲",
    "How many do you even need": "你到底需要多少",
    "How many left?": "还剩多少？",
    "Hyperboosts": "超能助力",
    "I need them all!": "我都需要！",
    "I've ran out of rebirth names": "我已经没有重生的名字了",
    "Increase point gain based on prestige points": "根据声望点数增加点数增益",
    "Layer 3 multi-boosts": "第3层多重提升",
    "Layer Expansion.?": "层扩张。?",
    "Maximum Handicaps": "最大的障碍",
    "Maximum Handicaps.. plus one": "最大的障碍。+ 1",
    "More upgrades": "更多的升级",
    "More upgrades!": "更多的升级!",
    "New Challenges Await": "新的挑战等待着我们",
    "New Layer!": "新层!",
    "New minirebirth!": "新迷你重生!",
    "New rebirth!": "新的重生!",
    "Obtain 18 collapse upgrades": "获得18次坍缩升级",
    "Obtain 1e22 points or more without resetting in the U layer or buying any upgrades in the U layer": "在不重置U层或不购买U层升级的情况下获得1e22分或以上",
    "Obtain 6 rebirth points": "获得6个重生点",
    "Obtain a booster": "获得一个助推器",
    "Obtain a decillion [1e30] Points": "获得1千分之一[1e30]点数",
    "Obtain a milestone point": "获得一个里程碑点",
    "Obtain a total of 5 energy points or more": "获得5点或更多能量点",
    "Obtain a upgrade point": "获得一个升级点",
    "Obtain an energy point": "获得一个能量点",
    "Obtain five milestone points": "获得五个里程碑点",
    "Obtain five rebirth points": "获得五个重生点",
    "Obtain four milestone points": "获得4个里程碑点",
    "Obtain four rebirth points at once": "一次获得四个重生点",
    "Obtain four upgrade points": "获得4个升级点",
    "Obtain seven rebirth points": "获得7个重生点",
    "Obtain ten booster points": "获得10个助推器点数",
    "Obtain ten collapse upgrades": "获得10次坍缩升级",
    "Obtain three booster points at once": "一次获得三个助推器点",
    "Obtain three milestone points": "获得三个里程碑点",
    "Obtain three upgrade points": "获得3个升级点",
    "Octa sacrifices": "八面体的牺牲",
    "One layer beats them all": "一层就能打败所有人",
    "Persistance": "暂留",
    "Pointful yet Pointless": "有意义却毫无意义",
    "Power collector": "权力收集器",
    "prestige points": "声望点",
    "Quadrupled sacrifices": "翻了两番的牺牲",
    "Rebirth Eight": "重生8",
    "Rebirth Four": "重生4",
    "Rebirth three": "重生3",
    "Rebirth two": "重生2",
    "Sacrifice Master": "牺牲大师",
    "Sacrifices": "牺牲",
    "Second upgrade Layer": "第二次升级层",
    "Septa sacrifices": "隔膜的牺牲",
    "So many Upgrades": "如此多的升级",
    "The start of a new layer!": "开始一个新的图层！",
    "The Start of a New Rebirth": "新重生的开始",
    "too much QoL": "过多的生活质量",
    "Triple Sacrifices": "三重牺牲",
    "Triplets": "三胞胎",
    "Triplets! Again..": "三胞胎!再一次。",
    "Two Energy Surges": "两次能量激增",
    "Two of the same digits": "两个相同的数字",
    "Uh oh": "哦哦",
    "Unlock Void": "打开空白",
    "Upgradeless twos": "无升级二",
    "v1.10d": "v1.10d",
    "wait, what??": "等等,什么? ?",
    "What's this?": "这是什么?",
    "What's this..?": "这是什么. . ?",
    "Increase point gain based on rebirth points": "基于重生点数增加点数",
    "Points will slightly boost themselves.": "点数会略微提升自身。",
    "Respec all upgrades": "重洗全部升级",
    "Reset previous progress for an upgrade point.": "重置之前的进度获得升级点。",
    "This will refund all upgrades and force an upgrade reset": "这将退还所有升级并强制升级重置",
    "upgrade points": "升级点数",
    "Upgrades": "升级",
    "Milestone 4 is harder to get but unlocks 2 more upgrades": "里程碑4更难获得，但可以解锁更多升级",
    "Milestone 3's formula is better": "里程碑3的公式更好",
    "Milestone 2's formula is changed and it multiplies point gain.": "里程碑2的公式改变了，它乘以点数增益。",
    "Milestone 1 also boosts prestige gain by 3x": "里程碑1也将声望增益提升3x",
    "Multiply point gain based on prestige points": "乘以点数增益基于声望点数",
    "Multiplies point gain based on Rebirth Points": "乘以点数增益基于重生点数",
    "Also gain x3 prestige points.": "同时获得x3声望点。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "=> RP": "=> 重生点数",
    "RP": "重生点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "requirement ": "要求 ",
    "Currently: x": "当前: x",
    "PP^": "声望点数^",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (base)": " (基础)",
    " Point Boost": " 点数提升",
    " Prestige Boost": " 声望提升",
    " Self-Synergy": " 自我协同",
    " Upgrade Points": " 升级点数",
    " Duplication": " 复制",
    " Scaling boost": " 缩放提升",
    " (Milestone 4+)": " (里程碑 4+)",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Costs (.+) upgrade point$/, '成本 $1 升级点数'],
    [/^Unlock (.+) Upgrades$/, '解锁 $1 升级'],
    [/^Have (.+) Rebirths$/, '重生 $1 次'],
    [/^Get (.+) rebirth$/, '获得 $1 重生'],
    [/^Get (.+) rebirths$/, '获得 $1 重生'],
    [/^Get (.+) energy$/, '获得 $1 能量'],
    [/^Get (.+) energy points$/, '获得 $1 能量点数'],
    [/^get (.+) mini rebirth points$/, '获得 $1 迷你重生点数'],
    [/^get (.+) points$/, '获得 $1 点数'],
    [/^Get (.+) collapse points$/, '获得 $1 坍缩点数'],
    [/^Get (.+) milestone points$/, '获得 $1 里程碑点数'],
    [/^Get (.+) mini rebirths.$/, '获得 $1 迷你重生。'],
    [/^Get (.+) mini rebirth points$/, '获得 $1 迷你重生点数'],
    [/^Get (.+) mini rebirths$/, '获得 $1 迷你重生'],
    [/^Obtain (.+) booster points or more$/, '获得 $1 或更多的助推器点数'],
    [/^Reach (.+) points to unlock \(You have (.+) points\)$/, '达到 $1 点数以解锁 \(你有 $2 点数\)'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^x([\d\.]+) point gain$/, 'x$1 点数增益'],
    [/^x([\d\.]+) prestige point gain$/, 'x$1 声望点数增益'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Achievements$/, '$1 成就'],
    [/^Rebirth r([\d\.,]+)$/, '重生 r$1'],
    [/^Milestone ([\d\.,]+)\+$/, '里程碑 $1\+'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Start gaining points at (.+) points per second$/, '初始点数增益 $1 点数每秒'],
    [/^(.+) points per second$/, '$1 点数每秒'],
    [/^(.+) Prestige Points$/, '$1 声望点'],
    [/^(.+) Prestige Point$/, '$1 声望点'],
    [/^Currently: (.+) point gain$/, '当前：$1 点数增益'],
    [/^Requirement: (.+) points.$/, '要求：$1 点数。'],
    [/^Cost: (.+) prestige points$/, '成本：$1 声望点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);